#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "terraforming-mars"
name = "Terraforming Mars "
description.en = "Implementation of Terraforming Mars board game"
description.fr = "Implementation du jeu de plateau Terraforming Mars"

version = "2026.08.01~ynh1"

maintainers = ["Thovi98"]

[upstream]
license = "GPL-3.0"
demo = "https://terraforming-mars.herokuapp.com/"
code = "https://github.com/terraforming-mars/terraforming-mars"

[integration]
yunohost = ">= 12.1.38"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/example"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

 [resources]

    [resources.sources]

      [resources.sources.main]
        url = "https://github.com/terraforming-mars/terraforming-mars/archive/ffe560149789960284e84ecc158f8b44dc274d44.tar.gz"
        sha256 = "bf2408de8612627382fca173c4d5965b67150e256ad4a5d12f4a0d9c9e52591f"
        in_subdir = true
        autoupdate.strategy = "latest_github_commit"
   
    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]

    main.url = "/"

    [resources.ports]
    main.default = 8080

    [resources.apt]
    packages = "postgresql, postgresql-contrib"
       
    [resources.database]
    type = "postgresql"

    [resources.nodejs]
    version = "24"
