#!/bin/bash


source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$install_dir"

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression "Configuring NGINX web server..."

# Create a dedicated NGINX config
ynh_config_add_nginx

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration..."

key=$(ynh_string_random --length=8 | base64)
ynh_app_setting_set --key=key --value=$key

ynh_config_add --template=".env" --destination="$install_dir/.env"

#=================================================
# BUILD APP
#=================================================

pushd $install_dir

	ynh_script_progression "npm install... This can be very long, be patient !"
	ynh_hide_warnings ynh_exec_as_app npm ci --quiet --production --prefer-offline --network-timeout=100000
	ynh_hide_warnings ynh_exec_as_app npm install --save-dev @types/html-escaper

	ynh_script_progression "npm run build... This can be very long, be patient !"
	SOURCE_VERSION="$(cat $YNH_APP_BASEDIR/manifest.toml | toml_to_json | jq -r ".resources.sources.main.url" | awk -F/ '{ print $NF }')"
	ynh_hide_warnings ynh_exec_as_app SOURCE_VERSION="$SOURCE_VERSION" npm run build
popd

#=================================================
# SETUP SYSTEMD
#=================================================
ynh_script_progression "Configuring $app's systemd service..."

# Create a dedicated systemd config
ynh_config_add_systemd

#=================================================
# LOGROTATE
#=================================================
ynh_script_progression "Configuring logrotate to manage application logfiles"

mkdir -p "/var/log/$app"
touch "/var/log/$app/$app.log"

# Use logrotate to manage application logfile(s)
ynh_config_add_logrotate

#=================================================
# INTEGRATE SERVICE IN YUNOHOST
#=================================================
ynh_script_progression "Integrating service in YunoHost..."

yunohost service add $app --description="Terraforming-Mars Service" --log=/var/log/$app/$app.log

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

# Start a systemd service
ynh_systemctl --service=$app --action="start"  --wait_until=""

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
